Adicionando .feature do exibir_historico_pedidos
silvaronald/ess-delivery-app pull request #1
Opened 2023-01-10 09:36 UTC by Edu-p

2023-01-26 16:27 UTC, silvaronald requested changes
Linha 1: Tem que trocar Recurso por Feature e faltou a parte do So that 
Deixa o nome do arquivo no formato ExibirHistoricoPedidos

2023-01-29 22:54 UTC, Edu-p commented
Fiz as alterações requeridas

2023-02-01 01:32 UTC, silvaronald requested changes

2023-02-01 01:32 UTC, silvaronald commented on features/ExibirHistoricoPedidos.feature
> +Recurso: visualizar histórico de pedidos
Pra funcionar na linguagem de testes acho que em vez de "Recurso" tem que ser "Feature" aqui

2023-02-12 10:46 UTC, Edu-p commented
Fiz as alterações requeridas

2023-02-12 15:11 UTC, merged