Adding Routes
silvaronald/ess-delivery-app pull request #32
Opened 2023-02-13 21:30 UTC by pedro-patriota

Falta Maria Beatriz colocar as rotas

2023-03-26 11:55 UTC, silvaronald requested changes

2023-03-26 11:55 UTC, silvaronald commented on web/src/components/login/Login.jsx
> +    console.log(check)
console.log

2023-03-26 11:55 UTC, silvaronald commented on web/src/components/restaurantMenu/RestaurantMenu.jsx
> +    console.log('a')
console.log

2023-03-29 21:29 UTC, pedro-patriota commented
Vê se vê meus componentes

2023-04-06 00:55 UTC, pedro-patriota commented
Tirei os console.logs e fiz a tela de login e de esqueci a senha

2023-04-06 00:56 UTC, closed without merging