Consertando logins da feature de total do mês e adicionando cenário de seleção de mês
silvaronald/ess-delivery-app pull request #40
Opened 2023-02-25 22:37 UTC by aqwer357

2023-03-06 22:57 UTC, silvaronald requested changes

2023-03-06 22:57 UTC, silvaronald commented on features/CalcularTotalDePedidosNoMes.feature
> +		Given estou logado como usuário "comPedidos"
Não entendi muito bem o que aconteceu nesse cenário e no de baixo. Tu tirou os pedidos que foram feitos, então agora tecnicamente não faz sentido aparecer 18,00 em Tonho se pela especificação não tem nenhum pedido nele mais.

2023-03-07 00:02 UTC, aqwer357 commented on features/CalcularTotalDePedidosNoMes.feature
> +		Given estou logado como usuário "comPedidos"
A conta vai estar configurada com os pedidos separadamente. Nós apenas validamos o total, portanto a única coisa no caso teste é isso.
Vai estar na db o restaurante/items e na db do cliente o pedido sacou?

Foi isso que o professor quis dizer com "login pronto"

2023-03-07 00:37 UTC, silvaronald commented on features/CalcularTotalDePedidosNoMes.feature
> +		Given estou logado como usuário "comPedidos"
Entendi, beleza!!

2023-03-07 00:40 UTC, silvaronald approved these changes

2023-03-07 00:40 UTC, merged